
version: 1.0.0-{build}

image: Visual Studio 2017

configuration: UMBHOST

before build: nuget restore

build: 
    publish_wap: true

deploy:
    provider: Environment
    name: UMBHOST.web-for-professionals.co.uk
    on:
      branch: main


environment:
  global:
    FTP_SERVER: "ftp.gb.umbhost.net"  # Replace with your FTP server address
    FTP_USERNAME: "webforpr_julius"  # Replace with your FTP username
    FTP_PASSWORD: "yLehspadwit0@kgufvjq"  # Replace with your FTP password
    ASPNETCORE_ENVIRONMENT: "Production"  # Optional: Set to "Production" for production environment

