version: 1.0.0-{build}
image: Visual Studio 2017
configuration: UAT
cache: 
    - packages -> **\packages.config
before_build: nuget restore
build: 
    publish_wap: true
deploy:
 provider: Environment
 name: UMBHOST.web-for-professionals.co.uk
 on:
   branch: master