
version: 1.0.0-{build}
image: Visual Studio 2022
configuration: UAT

before_build:
  - dotnet restore

build_script:
  - dotnet publish -c UAT -o output

deploy:
  provider: Environment
  name: UMBHOST.web-for-professionals.co.uk
  on:
    branch: main