version: 1.0.{build}

environment:
  global:
    FTP_SERVER: "ftp.gb.umbhost.net"  # Replace with your FTP server address
    FTP_USERNAME: "webforpr_julius"  # Replace with your FTP username
    FTP_PASSWORD: "yLehspadwit0@kgufvjq"  # Replace with your FTP password
    ASPNETCORE_ENVIRONMENT: "Production"  # Optional: Set to "Production" for production environment

image: mcr.microsoft.com/dotnet/core/sdk:8.0

environment:
  matrix:
    - DOTNET_VERSION: '8.0'

install:
  - ps: dotnet --version  # Check the installed version of .NET SDK
  - ps: dotnet restore packages/Demo.Web/Demo.Web.csproj

build:
  project: packages/Demo.Web/Demo.Web.csproj
  verbosity: minimal
  target: Build

version: 1.0.{build}

clone_depth: 1  # Clone only the latest commit for faster build times

install:
  - ps: Install-Product -Name 'dotnet' -Version $Env:DOTNET_VERSION -Force

build:
  project: Demo.Web/Demo.Web.csproj
  verbosity: minimal
  target: Build

  script:
    - ps: dotnet restore Demo.Web.csproj  # Now pointing to the root location
    - ps: dotnet build Demo.Web.csproj  # Now pointing to the root location
    - ps: dotnet publish Demo.Web.csproj --configuration Release --output $APPVEYOR_BUILD_FOLDER\publish  # Publish the output

deploy:
  provider: FTP
  server: $FTP_SERVER
  username: $FTP_USERNAME
  password: $FTP_PASSWORD
  remote_path: /Web-For-Professionals.co.uk_WTJ1EPDM/wwwroot  # Update with your correct path
  artifact: $APPVEYOR_BUILD_FOLDER\publish  # Path to your published output
  on:
    branch: main