version: 1.0.{build}

environment:
  global:
    FTP_SERVER: "ftp.gb.umbhost.net"  # Replace with your FTP server address
    FTP_USERNAME: "webforpr_julius"  # Replace with your FTP username
    FTP_PASSWORD: "yLehspadwit0@kgufvjq"  # Replace with your FTP password
    ASPNETCORE_ENVIRONMENT: "Production"  # Optional: Set to "Production" for production environment

image: Visual Studio 2022

install:
  - ps: Install-Product node 14 x64
  - ps: |
      $ErrorActionPreference = 'Stop'
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
      .\dotnet-install.ps1 -Channel 8.0
  - ps: dotnet --list-sdks  # Verify installed SDKs
  - ps: dotnet --version  # Verify .NET CLI version

build_script:
  - ps: dotnet build "C:\projects\portfolioumbraco\Demo.Web.csproj" /verbosity:minimal

test_script:
  - ps: dotnet test "C:\projects\portfolioumbraco\Demo.Web.csproj"
  
deploy:
  provider: FTP
  server: $FTP_SERVER
  username: $FTP_USERNAME
  password: $FTP_PASSWORD
  remote_path: /Web-For-Professionals.co.uk_WTJ1EPDM/wwwroot  # Update with your correct path
  artifact: $APPVEYOR_BUILD_FOLDER\publish  # Path to your published output
  on:
    branch: main